#!/usr/bin/env node
// =====================================================================
// Attach REAL beach geometry to CIIN beach segments.
//
// Sources OpenStreetMap `natural=beach` features — actual mapped beaches, not
// the coastline. (An earlier pass traced natural=coastline, which is the
// land/water boundary: it runs along harbour walls and river mouths and is not
// a beach front.) Data © OpenStreetMap contributors, ODbL.
//
// Two modes, because picking WHICH beach a segment is cannot be automated
// honestly — "Long Bay" and "North cove" are local names that only someone who
// knows the coast can match to an OSM feature:
//
//   1. node scripts/beachfront.mjs --candidates segments.json
//      Lists nearby mapped beaches per segment, with OSM ids and distances.
//      A human picks, and writes the chosen id into segments.json as "osm".
//
//   2. node scripts/beachfront.mjs segments.json > backfill.sql
//      Fetches the geometry of each chosen feature and emits UPDATE statements.
//      Writes nothing itself — the SQL is reviewable before it lands.
//
// segments.json entry: { id, name, lat, lng, length_m, osm?: "way/578136135" }
// =====================================================================

const ENDPOINT = 'https://overpass-api.de/api/interpreter'
const UA = 'CIIN-CaribbeanSargassumNetwork/1.0 (beachfront backfill; contact: ops@watersolutions.example)'
const R_EARTH_M = 6371000
const sleep = (ms) => new Promise(r => setTimeout(r, ms))

function metres(a, b) {
  const toRad = (d) => (d * Math.PI) / 180
  const dLat = toRad(b.lat - a.lat), dLon = toRad(b.lon - a.lon)
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLon / 2) ** 2
  return 2 * R_EARTH_M * Math.asin(Math.sqrt(h))
}

// Overpass is a free shared service: back off rather than hammer it. A
// 406/429/504 is throttling, not an absent beach.
async function overpass(query, attempt = 0) {
  const r = await fetch(ENDPOINT, { method: 'POST', body: 'data=' + encodeURIComponent(query),
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': UA, Accept: 'application/json' } })
  if (!r.ok) {
    if ([406, 429, 502, 504].includes(r.status) && attempt < 4) {
      await sleep(2500 * (attempt + 1))
      return overpass(query, attempt + 1)
    }
    throw new Error(`Overpass ${r.status}`)
  }
  return r.json()
}

const near = (lat, lng, radius) =>
  `[out:json][timeout:40];(way(around:${radius},${lat},${lng})["natural"="beach"];` +
  `relation(around:${radius},${lat},${lng})["natural"="beach"];);out tags center;`

const byId = (osm) => {
  const [type, id] = String(osm).split('/')
  return `[out:json][timeout:40];${type}(${id});out geom;`
}

async function candidates(segments) {
  for (const s of segments) {
    const j = await overpass(near(s.lat, s.lng, 6000))
    const rows = (j.elements || [])
      .map(e => ({ osm: `${e.type}/${e.id}`, name: e.tags?.name || '(unnamed)',
                   m: e.center ? Math.round(metres({ lat: s.lat, lon: s.lng }, e.center)) : Infinity }))
      .sort((a, b) => a.m - b.m)
    console.log(`\n${s.name}  (stored at ${s.lat}, ${s.lng})`)
    if (!rows.length) { console.log('  no mapped beach within 6 km'); continue }
    for (const r of rows.slice(0, 10)) console.log(`  ${r.osm.padEnd(18)} ${r.name.padEnd(30)} ${r.m} m away`)
    console.log('  ^ put the chosen id in segments.json as "osm"')
    await sleep(1500)
  }
}

const sqlStr = (v) => "'" + String(v).replace(/'/g, "''") + "'"

async function emit(segments) {
  const log = (m) => process.stderr.write(m + '\n')
  console.log('-- beach_segments.path backfill — real beach geometry from OpenStreetMap')
  console.log('-- natural=beach features, ODbL. Generated by scripts/beachfront.mjs')
  console.log(`-- ${new Date().toISOString()}`)
  console.log('begin;')

  for (const s of segments) {
    if (!s.osm) { log(`-- ${s.name}: no "osm" chosen — run --candidates first; left untraced`); continue }
    let el
    try {
      const j = await overpass(byId(s.osm))
      el = (j.elements || [])[0]
    } catch (e) { log(`!! ${s.name}: ${e.message}`); continue }

    const geom = el?.geometry || el?.members?.flatMap(m => m.geometry || [])
    if (!geom?.length) { log(`!! ${s.name}: ${s.osm} returned no geometry`); continue }

    const coords = geom.map(p => [Number(p.lat.toFixed(6)), Number(p.lon.toFixed(6))])
    const centre = { lat: coords.reduce((a, c) => a + c[0], 0) / coords.length,
                     lon: coords.reduce((a, c) => a + c[1], 0) / coords.length }
    const off = Math.round(metres({ lat: s.lat, lon: s.lng }, centre))
    const closed = coords.length > 3 &&
      coords[0][0] === coords[coords.length - 1][0] && coords[0][1] === coords[coords.length - 1][1]

    log(`ok ${s.name}: ${s.osm} "${el.tags?.name || '(unnamed)'}" — ${coords.length} pts, ` +
        `${closed ? 'area' : 'line'}, centre ${off} m from the stored coordinate` +
        (off > 500 ? '   <-- stored lat/lng is well off this beach; consider correcting it' : ''))

    console.log(`-- ${s.name} <- ${s.osm} ${el.tags?.name ? `"${el.tags.name}"` : ''} (${closed ? 'area' : 'line'}, ${coords.length} pts)`)
    console.log(`update beach_segments set path = ${sqlStr(JSON.stringify(coords))}::jsonb where id = ${sqlStr(s.id)}::uuid;`)
  }
  console.log('commit;')
}

async function main() {
  const args = process.argv.slice(2)
  const wantCandidates = args.includes('--candidates')
  const file = args.find(a => !a.startsWith('--'))
  if (!file) { process.stderr.write('usage: beachfront.mjs [--candidates] segments.json\n'); process.exit(2) }
  const segments = JSON.parse(await (await import('node:fs/promises')).readFile(file, 'utf8'))
  await (wantCandidates ? candidates(segments) : emit(segments))
}
main().catch(e => { process.stderr.write('failed: ' + e.message + '\n'); process.exit(1) })
