-- ---------------------------------------------------------------
-- Backfill: traced shoreline geometry for the seeded beach segments.
-- Generated by scripts/coastline.mjs from OpenStreetMap natural=coastline
-- (ODbL — attribution is carried on the map caption). Re-runnable: it sets
-- `path` by id, so running it twice is a no-op rather than a duplicate.
--
-- NOT INCLUDED, deliberately: "Long Bay — main frontage". The nearest OSM
-- coastline is 1655 m from its stored coordinate, which is too far to be that
-- segment's shore. Rather than attach the wrong shoreline, it stays untraced
-- and the map keeps showing it as a point. See the note in 0018.
-- "North cove" traced at 1080 m off the line — accepted but worth checking;
-- its stored coordinate looks like representative seed data, not a survey.
-- ---------------------------------------------------------------
-- beach_segments.path backfill — traced from OpenStreetMap coastline (ODbL).
-- generated 2026-09-06T23:59:21.864Z by scripts/coastline.mjs
begin;
-- North cove: 19 pts, 188m
update beach_segments set path = '[[18.337989,-78.348404],[18.337938,-78.348435],[18.337869,-78.348481],[18.337831,-78.348518],[18.337802,-78.348546],[18.337724,-78.348566],[18.337655,-78.348551],[18.337574,-78.348488],[18.33752,-78.348412],[18.337468,-78.348347],[18.337407,-78.34828],[18.337342,-78.348204],[18.337322,-78.348129],[18.337336,-78.348043],[18.337349,-78.347898],[18.337321,-78.347771],[18.33728,-78.347616],[18.337287,-78.347516],[18.337371,-78.34734]]'::jsonb where id = '54287290-07fa-4ea0-b2d8-6383255f5fea'::uuid;
-- North cove (duplicate row): 19 pts, 188m
update beach_segments set path = '[[18.337989,-78.348404],[18.337938,-78.348435],[18.337869,-78.348481],[18.337831,-78.348518],[18.337802,-78.348546],[18.337724,-78.348566],[18.337655,-78.348551],[18.337574,-78.348488],[18.33752,-78.348412],[18.337468,-78.348347],[18.337407,-78.34828],[18.337342,-78.348204],[18.337322,-78.348129],[18.337336,-78.348043],[18.337349,-78.347898],[18.337321,-78.347771],[18.33728,-78.347616],[18.337287,-78.347516],[18.337371,-78.34734]]'::jsonb where id = '1bd21129-164b-417f-a30e-a8178b2d8f53'::uuid;
-- San Juan PR — main frontage: 11 pts, 429m
update beach_segments set path = '[[18.463473,-66.106938],[18.463588,-66.106863],[18.463717,-66.106776],[18.464782,-66.106105],[18.464726,-66.105896],[18.464791,-66.105872],[18.464673,-66.105441],[18.463706,-66.106052],[18.463676,-66.105989],[18.463659,-66.106003],[18.463307,-66.106225]]'::jsonb where id = 'bf1c4aa1-9d34-41ec-89c9-15b92761666b'::uuid;
commit;
